<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Composite-toffoli" data-toc-modified-id="Composite-toffoli-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Composite toffoli</a></span></li></ul></div>

In [1]:
import numpy as np
from qutip import*

In [17]:
toffoli()

<ipython-input-17-28a803e4b529>:1: DeprecationWarning: Importing functions/classes of the qip submodule directly from the namespace qutip is deprecated. Please import them from the submodule instead, e.g.
from qutip.qip.operations import cnot
from qutip.qip.circuit import QubitCircuit

  toffoli()


Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]

In [14]:
#XII
gate0 = qeye(3)
gate0 = np.array(gate0)
gate0[0,0] = 0
gate0[1,1] = 0
gate0[0,1] = 1
gate0[1,0] = 1
gate0 = Qobj(gate0)
gate0 = tensor(gate0, qeye(3), qeye(3))
gate0 = Qobj(np.array(gate0))

#11x-02x iswap
gate1 = qeye(9)
gate1= np.array(gate1)
gate1[3,3] = 0
gate1[4,4] = 0
gate1[3,4] = 1j
gate1[4,3] = 1j
gate1 = Qobj(gate1)
gate1 = tensor(gate1, qeye(3))
gate1 = Qobj(np.array(gate1))

#CZ q1-q2
gate2 = qeye(9)
gate2= np.array(gate2)
gate2[3,3] = -1
gate2 = Qobj(gate2)
gate2 = tensor(qeye(3), gate2)
gate2 = Qobj(np.array(gate2))

#swap 02x-11x
gate3 = qeye(9)
gate3= np.array(gate3)
gate3[3,3] = 0
gate3[4,4] = 0
gate3[3,4] = 1
gate3[4,3] = 1
gate3 = Qobj(gate3)
gate3 = tensor(gate3, qeye(3))
gate3 = Qobj(np.array(gate3))

In [20]:
gate_ccz = gate1*gate2*gate3
gate_ccz = Qobj(gate_toff[0:8,0:8])  

In [22]:
gate_ccz.dims = [[2,2,2], [2,2,2]]

In [23]:
gate_toff.dims

[[2, 2, 2], [2, 2, 2]]

In [29]:
gate_toff = tensor(sigmax(),qeye(2), qeye(2))*gate_toff

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]]